const Case13 = () => {
  return (
    <div className="case-study">
      <header className="case-header">
        <span className="case-number">Use Case 13</span>
        <h1>The Freemium Whale Trap</h1>
        <div className="case-meta">Industry: Gaming / B2C Mobile App &bull; Level: Executive / Strategic</div>
      </header>

      {/* ── SECTION 1: EXECUTIVE BRIEFING ── */}
      <section>
        <h2>1. Executive Briefing: The Fragility Report</h2>
        <div className="content">
          <p>
            <strong>QuestBound</strong> is a top-grossing mobile RPG. On paper, the business is booming with $12M Monthly Recurring Revenue (MRR). However, we have identified a <strong>Critical Concentration Risk</strong>.
          </p>
          <div className="highlight-box">
            <strong>The Situation:</strong> While total revenue is stable, 94% of our income is generated by 0.2% of our players ("Whales"). 
            <br />
            <strong>The Danger:</strong> Our "Payer Base" is an inverted pyramid. We are one "bad update" away from a 50% revenue collapse if just 100 individuals decide to leave.
          </div>
          <p>
            Current strategy focuses on "Whale Hunting" (high-ticket items). This analysis proposes a pivot to <strong>"Minnow Farming"</strong> (broad-base conversion).
          </p>
        </div>
      </section>

      {/* ── SECTION 2: THE PAYER PYRAMID ── */}
      <section>
        <h2>2. Revenue Distribution (The Gini Analysis)</h2>
        <div className="content">
          <p>
            We calculated the <strong>Gini Coefficient</strong>—a measure of inequality—of our revenue. A healthy game usually sits at 0.70; we are at 0.96.
          </p>
          <table className="data-table">
            <thead>
              <tr>
                <th>Segment</th>
                <th>% of Users</th>
                <th>Monthly Spend</th>
                <th>Total Rev Contribution</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Whales</strong></td>
                <td>0.2%</td>
                <td>$5,000+</td>
                <td><strong>94%</strong></td>
              </tr>
              <tr>
                <td><strong>Dolphins</strong></td>
                <td>1.8%</td>
                <td>$50 - $200</td>
                <td><strong>5.5%</strong></td>
              </tr>
              <tr>
                <td><strong>Minnows</strong></td>
                <td>3.0%</td>
                <td>$0.99 - $10</td>
                <td><strong>0.5%</strong></td>
              </tr>
              <tr>
                <td><strong>F2P (Free)</strong></td>
                <td>95%</td>
                <td>$0</td>
                <td><strong>0%</strong></td>
              </tr>
            </tbody>
          </table>
          <p style={{ marginTop: "15px" }}>
            <em>The Problem:</em> Our "Minnow" segment is virtually non-existent. We have failed to build a "Middle Class" of spenders.
          </p>
        </div>
      </section>

      {/* ── SECTION 3: THE FRICTION AUDIT ── */}
      <section>
        <h2>3. Why Don't People Spend $1?</h2>
        <div className="content">
          <p>
            We analyzed the <strong>First Purchase Friction</strong>. We found that the psychological gap between $0 and $0.99 is 10x larger than the gap between $10 and $100.
          </p>
          <ul>
            <li><strong>The "High-Entry" Barrier:</strong> Our lowest shop item is $4.99. This is too high for a "test" purchase.</li>
            <li><strong>The Pay-to-Win Stigma:</strong> F2P players feel that spending small amounts doesn't help them compete with Whales, so they don't spend at all.</li>
            <li><strong>Lack of "Micro-Utility":</strong> We lack consumable items that provide immediate, low-cost satisfaction (e.g., "energy refills" or "cosmetic badges").</li>
          </ul>
        </div>
      </section>

      {/* ── SECTION 4: REVENUE SENSITIVITY (SCENARIO MODELING) ── */}
      <section>
        <h2>4. Risk Modeling: "The Exodus Effect"</h2>
        <div className="content">
          <p>We simulated three scenarios to show the Board why the status quo is dangerous.</p>
          <div className="calculation">
{`Scenario A: Loss of 50 Top Whales (Churn)
  Impact: -$250,000 MRR | Total Revenue Drop: 12%
  
Scenario B: 10% Increase in "Whale" Pricing
  Impact: +$1M Revenue, but +15% Whale Churn (Net Neutral/Negative long-term)
  
Scenario C: Convert 5% of F2P to Minnows ($1.99 Starter Pack)
  Impact: +$950,000 MRR | Total Revenue Drop: +8%
  RESULT: Scenario C creates the highest "Revenue Floor" stability.`}
          </div>
        </div>
      </section>

      {/* ── SECTION 5: THE "MIDDLE-CLASS" PLAYBOOK ── */}
      <section>
        <h2>5. Strategic Interventions (The Value Ladder)</h2>
        <div className="content">
          <p>To fix the trap, we are deploying a three-tiered <strong>Monetization Ladder</strong>.</p>
          
          <div className="highlight-box">
            <strong>Tier 1: The "First-Dollar" Hook (Minnows)</strong>
            <ul>
              <li><strong>The "Breaking the Ice" Pack:</strong> A $0.99 one-time offer with 500% value. Purpose: Get the credit card on file.</li>
              <li><strong>Reward:</strong> Instant-unlock cosmetic + 24hr XP boost.</li>
            </ul>
          </div>

          <div className="highlight-box">
            <strong>Tier 2: The "Habit" Builder (Dolphins)</strong>
            <ul>
              <li><strong>Battle Pass (Monthly):</strong> $9.99 for a month of progression. Purpose: Increase retention (DAU) through "sunk cost" mechanics.</li>
            </ul>
          </div>

          <div className="highlight-box">
            <strong>Tier 3: The "Prestige" Layer (Whales)</strong>
            <ul>
              <li><strong>Exclusive Auctions:</strong> Limited edition skins. Purpose: Capture "uncapped" spend from those who have already maxed out their power.</li>
            </ul>
          </div>
        </div>
      </section>

      {/* ── SECTION 6: IMPLEMENTATION & TRACKING ── */}
      <section>
        <h2>6. Tracking the Pivot (Leading Indicators)</h2>
        <div className="content">
          <p>We are shifting our "North Star" from ARPU (Average Revenue Per User) to <strong>Payer Conversion Rate (PCR)</strong>.</p>
          <table className="data-table">
            <thead>
              <tr>
                <th>Metric</th>
                <th>Current</th>
                <th>Target (6 Months)</th>
                <th>Why it Matters</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><strong>Payer Conversion</strong></td>
                <td>0.8%</td>
                <td>4.5%</td>
                <td>Reduces dependence on Whales</td>
              </tr>
              <tr>
                <td><strong>Gini Coefficient</strong></td>
                <td>0.96</td>
                <td>0.75</td>
                <td>Measures revenue health/equality</td>
              </tr>
              <tr>
                <td><strong>Avg Minnow LTV</strong></td>
                <td>$2.40</td>
                <td>$12.00</td>
                <td>Moves players up the ladder</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>

      {/* ── SECTION 7: PROFESSIONAL ANALYST MINDSET ── */}
      <section>
        <h2>7. Strategic Insight: The "Ecosystem" View</h2>
        <div className="content">
          <p>
            <strong>Senior Perspective:</strong> In freemium models, <strong>F2P players are not "freeloaders"—they are the content.</strong> Without a massive F2P and Minnow population for Whales to play with/against, the Whales get bored and leave.
          </p>
          <div className="highlight-box">
            <strong>Key Takeaway:</strong> A business that relies on a few "super-users" is a fragile business. The job of the analyst is not just to increase revenue, but to <strong>increase the quality and stability of that revenue</strong>. By converting a F2P user to a $1 spender, you aren't just gaining $1; you are significantly increasing the probability that they will still be playing (and spending) six months from now.
          </div>
        </div>
      </section>
    </div>
  );
};

export default Case13;